### ISSUE TITLE
Really easy to click on directories when scrolling

### ISSUE THREAD

**Issue by stuaxo** [kivy-garden/garden.filebrowser#13]
I find it almost impossible to navigate a folder with lots of subfolders in the list view as I keep going into subfolders by accident.

**Comment by stuaxo** [comment]
Combined with #14 this makes the list view pretty unusable for me.

Icon view is ok as I can scroll in an area without any icons in it.

**Comment by stuaxo** [comment]
(more info - am using this in kivy designer)

**Comment by stuaxo** [comment]
This might actually be this problem:   https://github.com/kivy/kivy/issues/3707

**Comment by matham** [comment]
This is not specific to filebrowser and seems to have already been fixed in any case.

**Comment by stuaxo** [comment]
Yup, cheers for closing this - I should have remembered once 3703 was fixed.
