### ISSUE TITLE
Any idea why it takes seconds to load a directory

### ISSUE THREAD

**Issue by stuaxo** [kivy-garden/garden.filebrowser#14]
In a folder with 200 subdirectories, you can see the directory loading in a progress bar, any idea why it takes a visible amount of time ?

**Comment by matham** [comment]
It's a OS thing. It needs to enumerate and walk all these folders. It can be made nicer so that it lists files while it's still enumerating them but that would require a filechooser re-write and is out of scope of filebrowser.
