### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by WARTORIOUS** [kivy-garden/garden.filebrowser#19]
Solved: You need to change the text in the BAT file to make garden work:

change python.exe %~dp0garden %*
to ..\python.exe %~dp0garden %*

My bat file, (when we got it down from the ceiling) was here:
C:\Python34\Scripts\garden.bat

Hope this helps!

---

_Origanal post_

---

Hi. I'm using windows and have garden. How do I install this so it works with kivy-designer-master? 

can anyone make a plain english help file, i.e. 
GO TO CMD
CD C:\Python34\Lib\site-packages\kivy
TYPE ' garden install FileBrowser '
Something like that would be AMAZING. Please include EVERYTHING i need to type, no lazy shortcuts please. EVERYTHING.

**Comment by picibucor** [comment]
Working example on stackoverflow:
http://stackoverflow.com/questions/32439330/add-filebrowser-in-kivy/37613896#37613896

**Comment by matham** [comment]
That's because python needs to be on the `PATH` for any of it to work.

**Comment by ymongo** [comment]
best solution here: https://github.com/kivy/kivy/issues/5673
