### ISSUE TITLE
Editing filename does not work

### ISSUE THREAD

**Issue by mdurian** [kivy-garden/garden.filebrowser#26]
I was testing FileBrowser since it looked like it might provide a good interface for a user to select a save file (which might not already exist). FileBrowser provides a nice way to navigate directories and includes an editable TextInput, which the stock kivy FileChooser does not provide. However, when I tried directly editing the filename without selecting a file, upon on_success the selection property comes back as an empty list.

It would be great if FileBrowser could support editable filenames. If not, then maybe it makes sense to make the TextInput widget readonly.

**Comment by matham** [comment]
You can get the filename typed into the textbox by getting `self.filename`, where self is the filebrowser. It also has a `self.path` variable for the path.

**Comment by mdurian** [comment]
Thank you. I missed the filename property.
